apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  initdb.sql: |
    CREATE DATABASE bk;
    USE bk;
    CREATE TABLE IF NOT EXISTS `user` (
    `id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    `username` VARCHAR(50) NOT NULL UNIQUE COMMENT '用户昵称',
    `phone_number` CHAR(11) NOT NULL UNIQUE COMMENT '手机号',
    `password` VARCHAR(16) NOT NULL COMMENT '密码',
    `avatar` BLOB COMMENT '头像',
    `identity` VARCHAR(50) COMMENT '身份',
    `ip_position` VARCHAR(50) COMMENT 'ip属地',
    `created_at` DATETIME COMMENT '创建时间',
    `updated_at` DATETIME COMMENT '更新时间',
    `deleted_at` DATETIME COMMENT '删除时间',
  
    INDEX `username_index` (`username`),
    INDEX `phone_number_index` (`phone_number`)
    )ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='用户表';

---
apiVersion: v1
kind: Pod
metadata:
  name: bk-pod
  labels:
    app: bk
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
      volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d

    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017

    - name: redis
      image: redis
      ports:
        - containerPort: 6379

    - name: gateway
      image: zihzihzih/gateway
      ports:
        - containerPort: 15038

    - name: user
      image: zihzihzih/user
      ports:
        - containerPort: 15034

  volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb

#  initContainers:
#    - name: init-mysql
#      image: busybox
#      command: ['sh', '-c', 'cp /initdb/initdb.sql /docker-entrypoint-initdb.d/']
#      volumeMounts:
#        - name: mysql-initdb
#          mountPath: /initdb

---
apiVersion: v1
kind: Service
metadata:
  name: bk-service
spec:
  type: NodePort
  selector:
    app: bk
  ports:
    - port: 15038
      targetPort: 15038
      nodePort: 30007